### PR TITLE
ADD: Add new fields for AQ cookbook data portals

### PR DESCRIPTION
**Pull request by mgrover1**
Add in new fields required for AQS and NASA Earthdata environment variables

### CODE REVIEW

**Comment by mgrover1** [comment]
@brian-rose - this adds new environment variables required for the air quality cookbook. Can you please review + merge here? So we can test downstream to ensure the secrets are passed properly in the build?

**Comment by mgrover1** [comment]
@ktyle feel free to take a look as well!

**Comment by ktyle** [comment]
@mgrover1 this looks good but I'm a bit ignorant of how secrets should work in our workflows and actions. To test things, I created a fork of cookbook-actions based on your branch, and then added the AQS_USERNAME and AQS_KEY as secrets (using the email address and key that I received from the AQS site), based on https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions. I then forked the api-cookbook and created a PR (ktyle/api-cookbook#1) whose trigger-book-build action points to my fork of cookbook-actions. However, the build failed and it didn't seem like these two secrets were applied. 

Additionally, in our ProjectPythia/cookbook-actions repo, I don't see any secrets set.

What might I be missing?

**Comment by brian-rose** [comment]
As far as I understand things, @ktyle's build failure should be expected because builds triggered by a PR from a different org (in this case, an individual user) won't have access to secrets set in the upstream repository.

**Review by brian-rose — APPROVED** [review]
Approving the PR to enable testing. The `required: false` tags should mean that this won't break anything!

**Comment by brian-rose** [comment]
I will merge so @mgrover1 can test functionality! We can go back and fix things as necessary.

There's a clear need for a more modular system for declaring secrets so we don't have to specify every possibility in these reusable workflow. But we're not there yet.

**Comment by AMDeitsch** [comment]
> As far as I understand things, @ktyle's build failure should be expected because builds triggered by a PR from a different org (in this case, an individual user) won't have access to secrets set in the upstream repository.

Would this be the same issue with PR builds failing when sent from my fork to the Project Pythia cookbook? As far as I can tell, my builds are still failing when I push commits to my fork (and when PRs are initiated to the main repository).

**Comment by brian-rose** [comment]
@AMDeitsch Probably not, unless you are working with a cookbook that uses secrets for data access. Which cookbook repository are you opening PRs to?

**Comment by AMDeitsch** [comment]
Thanks, @brian-rose . It looks like @mgrover1 got the issue resolved in subsequent PRs.

**Pull request merged**
